"""Storage backend protocol.

One of the few interfaces the architecture doc says is worth having: development uses the local
filesystem, deployment may need S3-compatible storage, and tests want a tmp-dir instance. Keys
are opaque strings generated by the application — a client-supplied filename never becomes a
key or any part of one.
"""

from __future__ import annotations

from typing import Protocol


class StorageBackend(Protocol):
    async def save(self, key: str, content: bytes) -> None:
        """Persist `content` under `key`, creating any intermediate structure."""
        ...

    async def read(self, key: str) -> bytes:
        """Return the stored bytes. Raises FileNotFoundError when the key is absent."""
        ...

    async def delete(self, key: str) -> bool:
        """Remove the object. Returns False when it did not exist. Never raises for absence."""
        ...

    async def exists(self, key: str) -> bool: ...
