"""Local filesystem storage for development and the controlled demo.

File IO runs in a worker thread (`asyncio.to_thread`) so a large write never blocks the event
loop. Keys are validated against traversal even though they are server-generated — defence in
depth costs three lines.
"""

from __future__ import annotations

import asyncio
from pathlib import Path

from app.core.logging import get_logger

logger = get_logger(__name__)


class LocalStorage:
    def __init__(self, root: Path) -> None:
        self.root = root.resolve()

    def _path_for(self, key: str) -> Path:
        # Keys are generated by the application, but resolve-and-check anyway: if a bug ever
        # let hostile input reach here, it must not escape the upload root.
        candidate = (self.root / key).resolve()
        if not candidate.is_relative_to(self.root):
            raise ValueError(f"Storage key escapes the upload root: {key!r}")
        return candidate

    async def save(self, key: str, content: bytes) -> None:
        path = self._path_for(key)

        def _write() -> None:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(content)

        await asyncio.to_thread(_write)

    async def read(self, key: str) -> bytes:
        path = self._path_for(key)
        return await asyncio.to_thread(path.read_bytes)

    async def delete(self, key: str) -> bool:
        path = self._path_for(key)

        def _delete() -> bool:
            try:
                path.unlink()
                return True
            except FileNotFoundError:
                return False

        return await asyncio.to_thread(_delete)

    async def exists(self, key: str) -> bool:
        path = self._path_for(key)
        return await asyncio.to_thread(path.exists)
