"""company profile, evidence, and projects

Autogenerated, then reviewed by hand. The composite foreign keys on
(company_profile_id, owner_user_id) are the load-bearing part: they make "evidence cannot be
attached to another user's profile" a database guarantee rather than a service-layer check.

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-26

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "company_profiles",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("legal_name", sa.String(length=255), nullable=False),
        sa.Column("trading_name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=False),
        sa.Column("emirate", sa.String(length=32), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("year_established", sa.SmallInteger(), nullable=False),
        sa.Column("employee_count", sa.Integer(), nullable=False),
        sa.Column("years_of_experience", sa.SmallInteger(), nullable=False),
        sa.Column("trade_licence_number", sa.String(length=100), nullable=False),
        sa.Column("trade_licence_expiry", sa.Date(), nullable=False),
        sa.Column("licence_activities", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("contact_email", sa.String(length=320), nullable=False),
        sa.Column("contact_phone", sa.String(length=40), nullable=True),
        sa.Column("annual_revenue_range", sa.String(length=40), nullable=True),
        sa.Column("preferred_contract_value_min", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("preferred_contract_value_max", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("service_categories", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("geographic_coverage", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("profile_completion_percentage", sa.SmallInteger(), nullable=False),
        sa.Column("completion_version", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "annual_revenue_range IS NULL OR annual_revenue_range IN ('under_1m_aed', '1m_to_5m_aed', '5m_to_20m_aed', '20m_to_50m_aed', 'over_50m_aed')",
            name=op.f("ck_company_profiles_revenue_range"),
        ),
        sa.CheckConstraint(
            "emirate IN ('abu_dhabi', 'dubai', 'sharjah', 'ajman', 'umm_al_quwain', 'ras_al_khaimah', 'fujairah')",
            name=op.f("ck_company_profiles_emirate"),
        ),
        sa.CheckConstraint(
            "cardinality(geographic_coverage) >= 1",
            name=op.f("ck_company_profiles_geographic_coverage_present"),
        ),
        sa.CheckConstraint(
            "cardinality(service_categories) >= 1",
            name=op.f("ck_company_profiles_service_categories_present"),
        ),
        sa.CheckConstraint("employee_count >= 0", name=op.f("ck_company_profiles_employee_count")),
        sa.CheckConstraint(
            "preferred_contract_value_max IS NULL OR preferred_contract_value_max >= 0",
            name=op.f("ck_company_profiles_contract_max_positive"),
        ),
        sa.CheckConstraint(
            "preferred_contract_value_min IS NULL OR preferred_contract_value_max IS NULL OR preferred_contract_value_min <= preferred_contract_value_max",
            name=op.f("ck_company_profiles_contract_range"),
        ),
        sa.CheckConstraint(
            "preferred_contract_value_min IS NULL OR preferred_contract_value_min >= 0",
            name=op.f("ck_company_profiles_contract_min_positive"),
        ),
        sa.CheckConstraint(
            "profile_completion_percentage BETWEEN 0 AND 100",
            name=op.f("ck_company_profiles_completion_range"),
        ),
        sa.CheckConstraint(
            "year_established BETWEEN 1800 AND 2200",
            name=op.f("ck_company_profiles_year_established"),
        ),
        sa.CheckConstraint("years_of_experience >= 0", name=op.f("ck_company_profiles_experience")),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_company_profiles_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_profiles")),
        sa.UniqueConstraint("id", "owner_user_id", name="uq_company_profiles_id_owner_user_id"),
        sa.UniqueConstraint("owner_user_id", name="uq_company_profiles_owner_user_id"),
    )
    op.create_index("ix_company_profiles_emirate", "company_profiles", ["emirate"], unique=False)
    op.create_table(
        "company_evidence",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("company_profile_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("issuing_organisation", sa.String(length=255), nullable=True),
        sa.Column("reference_number", sa.String(length=120), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("verification_status", sa.String(length=24), nullable=False),
        sa.Column("verification_notes", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('trade_licence', 'certification', 'insurance', 'financial_statement', 'previous_project', 'client_reference', 'staff_cv', 'technical_capability', 'equipment_asset', 'policy', 'registration', 'other')",
            name=op.f("ck_company_evidence_category"),
        ),
        sa.CheckConstraint(
            "verification_status IN ('unverified', 'verified', 'rejected')",
            name=op.f("ck_company_evidence_verification_status"),
        ),
        sa.CheckConstraint("cardinality(tags) <= 20", name=op.f("ck_company_evidence_tag_count")),
        sa.CheckConstraint(
            "issue_date IS NULL OR expiry_date IS NULL OR issue_date <= expiry_date",
            name=op.f("ck_company_evidence_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id", "owner_user_id"],
            ["company_profiles.id", "company_profiles.owner_user_id"],
            name="fk_company_evidence_profile_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_evidence")),
    )
    op.create_index(
        "ix_company_evidence_expiry_date", "company_evidence", ["expiry_date"], unique=False
    )
    op.create_index(
        "ix_company_evidence_owner_category",
        "company_evidence",
        ["owner_user_id", "category"],
        unique=False,
    )
    op.create_index(
        "ix_company_evidence_owner_status",
        "company_evidence",
        ["owner_user_id", "verification_status"],
        unique=False,
    )
    op.create_index(
        "ix_company_evidence_profile_owner",
        "company_evidence",
        ["company_profile_id", "owner_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_company_evidence_tags",
        "company_evidence",
        ["tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_table(
        "company_projects",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("company_profile_id", sa.Uuid(), nullable=False),
        sa.Column("client_name", sa.String(length=255), nullable=False),
        sa.Column("project_title", sa.String(length=255), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("contract_value", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("location", sa.String(length=160), nullable=False),
        sa.Column("services_delivered", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("client_reference_available", sa.Boolean(), nullable=False),
        sa.Column("is_confidential", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'current' AND end_date IS NULL) OR (status = 'completed' AND end_date IS NOT NULL)",
            name=op.f("ck_company_projects_status_end_date"),
        ),
        sa.CheckConstraint(
            "status IN ('completed', 'current')", name=op.f("ck_company_projects_status")
        ),
        sa.CheckConstraint(
            "cardinality(services_delivered) >= 1",
            name=op.f("ck_company_projects_services_present"),
        ),
        sa.CheckConstraint(
            "contract_value IS NULL OR contract_value >= 0",
            name=op.f("ck_company_projects_contract_value"),
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR start_date <= end_date",
            name=op.f("ck_company_projects_date_order"),
        ),
        sa.ForeignKeyConstraint(
            ["company_profile_id", "owner_user_id"],
            ["company_profiles.id", "company_profiles.owner_user_id"],
            name="fk_company_projects_profile_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_projects")),
    )
    op.create_index(
        "ix_company_projects_owner_status",
        "company_projects",
        ["owner_user_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_company_projects_profile_owner",
        "company_projects",
        ["company_profile_id", "owner_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_company_projects_services",
        "company_projects",
        ["services_delivered"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_company_projects_start_date", "company_projects", ["start_date"], unique=False
    )


def downgrade() -> None:
    op.drop_index("ix_company_projects_start_date", table_name="company_projects")
    op.drop_index(
        "ix_company_projects_services", table_name="company_projects", postgresql_using="gin"
    )
    op.drop_index("ix_company_projects_profile_owner", table_name="company_projects")
    op.drop_index("ix_company_projects_owner_status", table_name="company_projects")
    op.drop_table("company_projects")
    op.drop_index("ix_company_evidence_tags", table_name="company_evidence", postgresql_using="gin")
    op.drop_index("ix_company_evidence_profile_owner", table_name="company_evidence")
    op.drop_index("ix_company_evidence_owner_status", table_name="company_evidence")
    op.drop_index("ix_company_evidence_owner_category", table_name="company_evidence")
    op.drop_index("ix_company_evidence_expiry_date", table_name="company_evidence")
    op.drop_table("company_evidence")
    op.drop_index("ix_company_profiles_emirate", table_name="company_profiles")
    op.drop_table("company_profiles")
