"""tenders and documents

Autogenerated, then reviewed. Documents carry the composite foreign key on
(tender_id, owner_user_id) plus a per-tender SHA-256 unique constraint for duplicate detection.

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-26

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "tenders",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("buyer", sa.String(length=255), nullable=True),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("submission_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("status IN ('active', 'archived')", name=op.f("ck_tenders_status")),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_tenders_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenders")),
        sa.UniqueConstraint("id", "owner_user_id", name="uq_tenders_id_owner_user_id"),
    )
    op.create_index(
        "ix_tenders_owner_deadline",
        "tenders",
        ["owner_user_id", "submission_deadline"],
        unique=False,
    )
    op.create_index("ix_tenders_owner_status", "tenders", ["owner_user_id", "status"], unique=False)
    op.create_index(op.f("ix_tenders_owner_user_id"), "tenders", ["owner_user_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("tender_id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=80), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("extraction_status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "extraction_status IN ('pending', 'extracted', 'failed', 'unsupported')",
            name=op.f("ck_documents_extraction_status"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_documents_size_positive")),
        sa.ForeignKeyConstraint(
            ["tender_id", "owner_user_id"],
            ["tenders.id", "tenders.owner_user_id"],
            name="fk_documents_tender_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_documents_storage_key")),
        sa.UniqueConstraint("tender_id", "sha256", name="uq_documents_tender_sha256"),
    )
    op.create_index("ix_documents_owner", "documents", ["owner_user_id"], unique=False)
    op.create_index(
        "ix_documents_tender_owner", "documents", ["tender_id", "owner_user_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index("ix_documents_tender_owner", table_name="documents")
    op.drop_index("ix_documents_owner", table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_tenders_owner_user_id"), table_name="tenders")
    op.drop_index("ix_tenders_owner_status", table_name="tenders")
    op.drop_index("ix_tenders_owner_deadline", table_name="tenders")
    op.drop_table("tenders")
