"""document pages

Autogenerated, then reviewed. Adds document_pages (the provenance unit for citations) and the
uniqueness on documents(id, owner_user_id) that its composite foreign key requires.

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-26

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # The unique constraint must exist before the composite foreign key that references it —
    # autogenerate emitted these in the wrong order.
    op.create_unique_constraint(
        "uq_documents_id_owner_user_id", "documents", ["id", "owner_user_id"]
    )
    op.create_table(
        "document_pages",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("character_count", sa.Integer(), nullable=False),
        sa.Column("quality_score", sa.Float(), nullable=False),
        sa.Column("extraction_method", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("page_number >= 1", name=op.f("ck_document_pages_page_number_positive")),
        sa.CheckConstraint(
            "quality_score >= 0 AND quality_score <= 1",
            name=op.f("ck_document_pages_quality_range"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id", "owner_user_id"],
            ["documents.id", "documents.owner_user_id"],
            name="fk_document_pages_document_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_pages")),
        sa.UniqueConstraint("document_id", "page_number", name="uq_document_pages_number"),
    )
    op.create_index(
        "ix_document_pages_document_owner",
        "document_pages",
        ["document_id", "owner_user_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_document_pages_document_owner", table_name="document_pages")
    op.drop_table("document_pages")
    op.drop_constraint("uq_documents_id_owner_user_id", "documents", type_="unique")
