"""analyses

Autogenerated, then reviewed. Adds the analyses table (job state machine) with the composite
ownership foreign key to tenders and a uq on (id, owner_user_id) for later findings.

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-26

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "analyses",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("tender_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("current_stage", sa.String(length=32), nullable=False),
        sa.Column("stage_message", sa.String(length=255), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=True),
        sa.Column("model", sa.String(length=80), nullable=True),
        sa.Column("prompt_version", sa.String(length=16), nullable=True),
        sa.Column("scoring_version", sa.String(length=16), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "current_stage IN ('queued', 'validating', 'extracting_text', 'assessing_quality', 'extracting_metadata', 'extracting_requirements', 'verifying_citations', 'matching_evidence', 'analysing_risks', 'scoring', 'generating_report', 'completed')",
            name=op.f("ck_analyses_stage"),
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'processing', 'completed', 'failed', 'cancelled')",
            name=op.f("ck_analyses_status"),
        ),
        sa.CheckConstraint("attempt_count >= 0", name=op.f("ck_analyses_attempt_count_positive")),
        sa.CheckConstraint(
            "input_tokens >= 0 AND output_tokens >= 0", name=op.f("ck_analyses_tokens_positive")
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_analyses_version_positive")),
        sa.ForeignKeyConstraint(
            ["tender_id", "owner_user_id"],
            ["tenders.id", "tenders.owner_user_id"],
            name="fk_analyses_tender_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analyses")),
        sa.UniqueConstraint("id", "owner_user_id", name="uq_analyses_id_owner_user_id"),
        sa.UniqueConstraint("tender_id", "version", name="uq_analyses_tender_version"),
    )
    op.create_index(
        "ix_analyses_owner_status", "analyses", ["owner_user_id", "status"], unique=False
    )
    op.create_index(
        "ix_analyses_tender_owner", "analyses", ["tender_id", "owner_user_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index("ix_analyses_tender_owner", table_name="analyses")
    op.drop_index("ix_analyses_owner_status", table_name="analyses")
    op.drop_table("analyses")
