"""requirements, citations, and tender metadata

Autogenerated, then reviewed. Adds requirements + requirement_citations + tender_metadata, each
with the composite ownership foreign key. requirements also gets uq(id, owner_user_id) so its
citations can carry the same composite-key guarantee.

Revision ID: 0007
Revises: 0006
Create Date: 2026-07-26

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "requirements",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("obligation", sa.String(length=16), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("expected_evidence", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("citation_verified", sa.Boolean(), nullable=False),
        sa.Column("machine_status", sa.String(length=24), nullable=False),
        sa.Column("reviewed_status", sa.String(length=24), nullable=False),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('legal_registration', 'certification', 'technical_capability', 'experience', 'staffing', 'financial', 'insurance', 'bid_bond_guarantee', 'submission_instruction', 'deadline', 'commercial', 'contractual', 'health_safety_environment', 'data_cybersecurity', 'other')",
            name=op.f("ck_requirements_category"),
        ),
        sa.CheckConstraint(
            "machine_status IN ('unreviewed', 'met', 'partially_met', 'not_met', 'needs_clarification', 'not_applicable')",
            name=op.f("ck_requirements_machine_status"),
        ),
        sa.CheckConstraint(
            "obligation IN ('mandatory', 'optional', 'uncertain')",
            name=op.f("ck_requirements_obligation"),
        ),
        sa.CheckConstraint(
            "reviewed_status IN ('unreviewed', 'met', 'partially_met', 'not_met', 'needs_clarification', 'not_applicable')",
            name=op.f("ck_requirements_reviewed_status"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_requirements_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id", "owner_user_id"],
            ["analyses.id", "analyses.owner_user_id"],
            name="fk_requirements_analysis_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirements")),
        sa.UniqueConstraint("id", "owner_user_id", name="uq_requirements_id_owner_user_id"),
    )
    op.create_index(
        "ix_requirements_analysis_category",
        "requirements",
        ["analysis_id", "category"],
        unique=False,
    )
    op.create_index(
        "ix_requirements_analysis_owner",
        "requirements",
        ["analysis_id", "owner_user_id"],
        unique=False,
    )
    op.create_table(
        "tender_metadata",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("buyer", sa.String(length=255), nullable=True),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("submission_deadline_text", sa.String(length=120), nullable=True),
        sa.Column("contract_duration", sa.String(length=120), nullable=True),
        sa.Column("estimated_value", sa.String(length=120), nullable=True),
        sa.Column("currency", sa.String(length=8), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id", "owner_user_id"],
            ["analyses.id", "analyses.owner_user_id"],
            name="fk_tender_metadata_analysis_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tender_metadata")),
        sa.UniqueConstraint("analysis_id", name=op.f("uq_tender_metadata_analysis_id")),
    )
    op.create_table(
        "requirement_citations",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("source_quote", sa.Text(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("match_method", sa.String(length=16), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "match_method IN ('exact', 'normalized', 'fuzzy', 'unverified', 'rejected')",
            name=op.f("ck_requirement_citations_match_method"),
        ),
        sa.CheckConstraint(
            "match_score IS NULL OR (match_score >= 0 AND match_score <= 1)",
            name=op.f("ck_requirement_citations_match_score_range"),
        ),
        sa.CheckConstraint(
            "page_number >= 1", name=op.f("ck_requirement_citations_page_number_positive")
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id", "owner_user_id"],
            ["requirements.id", "requirements.owner_user_id"],
            name="fk_requirement_citations_requirement_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_citations")),
    )
    op.create_index(
        "ix_requirement_citations_requirement_owner",
        "requirement_citations",
        ["requirement_id", "owner_user_id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_requirement_citations_requirement_owner", table_name="requirement_citations")
    op.drop_table("requirement_citations")
    op.drop_table("tender_metadata")
    op.drop_index("ix_requirements_analysis_owner", table_name="requirements")
    op.drop_index("ix_requirements_analysis_category", table_name="requirements")
    op.drop_table("requirements")
