"""evidence matches and risk findings

Autogenerated, then reviewed. Adds requirement_evidence_matches, risk_findings, and
risk_citations. risk_findings gets uq(id, owner_user_id) so its citations carry the same
composite-key ownership guarantee; the constraint must precede the citations table.

Revision ID: 0008
Revises: 0007
Create Date: 2026-07-26

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

revision: str = "0008"
down_revision: str | None = "0007"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "risk_findings",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("risk_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("why_it_matters", sa.Text(), nullable=False),
        sa.Column("suggested_action", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("citation_verified", sa.Boolean(), nullable=False),
        sa.Column("reviewed_status", sa.String(length=24), nullable=False),
        sa.Column("review_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "reviewed_status IN ('unreviewed', 'met', 'partially_met', 'not_met', 'needs_clarification', 'not_applicable')",
            name=op.f("ck_risk_findings_reviewed_status"),
        ),
        sa.CheckConstraint(
            "risk_type IN ('liquidated_damages', 'indemnity_liability', 'termination', 'payment_terms', 'performance_guarantee', 'bid_bond', 'insurance', 'data_privacy', 'intellectual_property', 'unclear_scope', 'aggressive_deadline', 'other')",
            name=op.f("ck_risk_findings_risk_type"),
        ),
        sa.CheckConstraint(
            "severity IN ('critical', 'high', 'medium', 'low')",
            name=op.f("ck_risk_findings_severity"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name=op.f("ck_risk_findings_confidence_range")
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id", "owner_user_id"],
            ["analyses.id", "analyses.owner_user_id"],
            name="fk_risk_findings_analysis_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_findings")),
        sa.UniqueConstraint("id", "owner_user_id", name="uq_risk_findings_id_owner_user_id"),
    )
    op.create_index(
        "ix_risk_findings_analysis_owner",
        "risk_findings",
        ["analysis_id", "owner_user_id"],
        unique=False,
    )
    op.create_table(
        "requirement_evidence_matches",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("requirement_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("matched_evidence_ids", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("missing_evidence", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("is_deterministic", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('met', 'partially_met', 'not_met', 'needs_clarification', 'not_applicable')",
            name=op.f("ck_requirement_evidence_matches_status"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1",
            name=op.f("ck_requirement_evidence_matches_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id", "owner_user_id"],
            ["requirements.id", "requirements.owner_user_id"],
            name="fk_evidence_matches_requirement_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_requirement_evidence_matches")),
    )
    op.create_index(
        "ix_evidence_matches_requirement",
        "requirement_evidence_matches",
        ["requirement_id", "owner_user_id"],
        unique=False,
    )
    op.create_table(
        "risk_citations",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("risk_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=False),
        sa.Column("source_quote", sa.Text(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("match_method", sa.String(length=16), nullable=False),
        sa.Column("match_score", sa.Float(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "match_method IN ('exact', 'normalized', 'fuzzy', 'unverified', 'rejected')",
            name=op.f("ck_risk_citations_match_method"),
        ),
        sa.CheckConstraint(
            "match_score IS NULL OR (match_score >= 0 AND match_score <= 1)",
            name=op.f("ck_risk_citations_match_score_range"),
        ),
        sa.CheckConstraint("page_number >= 1", name=op.f("ck_risk_citations_page_number_positive")),
        sa.ForeignKeyConstraint(
            ["risk_id", "owner_user_id"],
            ["risk_findings.id", "risk_findings.owner_user_id"],
            name="fk_risk_citations_risk_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_risk_citations")),
    )
    op.create_index(
        "ix_risk_citations_risk_owner", "risk_citations", ["risk_id", "owner_user_id"], unique=False
    )


def downgrade() -> None:
    op.drop_index("ix_risk_citations_risk_owner", table_name="risk_citations")
    op.drop_table("risk_citations")
    op.drop_index("ix_evidence_matches_requirement", table_name="requirement_evidence_matches")
    op.drop_table("requirement_evidence_matches")
    op.drop_index("ix_risk_findings_analysis_owner", table_name="risk_findings")
    op.drop_table("risk_findings")
