"""readiness assessments

Autogenerated, then reviewed. Adds the readiness_assessments table (deterministic score,
dimension breakdown, hard blockers, and human override) with the composite ownership FK.

Revision ID: 0009
Revises: 0008
Create Date: 2026-07-26

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql

revision: str = "0009"
down_revision: str | None = "0008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "readiness_assessments",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("analysis_id", sa.Uuid(), nullable=False),
        sa.Column("overall_score", sa.Numeric(precision=5, scale=1), nullable=False),
        sa.Column("decision_label", sa.String(length=32), nullable=False),
        sa.Column("dimension_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("hard_blockers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("assumptions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("calculation_version", sa.String(length=16), nullable=False),
        sa.Column("human_override_label", sa.String(length=32), nullable=True),
        sa.Column("human_override_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "decision_label IN ('strong_bid', 'conditional_bid', 'weak_bid', 'do_not_bid', 'insufficient_information')",
            name=op.f("ck_readiness_assessments_label"),
        ),
        sa.CheckConstraint(
            "human_override_label IS NULL OR human_override_label IN ('strong_bid', 'conditional_bid', 'weak_bid', 'do_not_bid', 'insufficient_information')",
            name=op.f("ck_readiness_assessments_override_label"),
        ),
        sa.CheckConstraint(
            "overall_score >= 0 AND overall_score <= 100",
            name=op.f("ck_readiness_assessments_overall_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["analysis_id", "owner_user_id"],
            ["analyses.id", "analyses.owner_user_id"],
            name="fk_readiness_analysis_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_readiness_assessments")),
        sa.UniqueConstraint("analysis_id", name=op.f("uq_readiness_assessments_analysis_id")),
    )


def downgrade() -> None:
    op.drop_table("readiness_assessments")
