"""portal marketplace: organisations, listings, applications, screening, notifications

Autogenerated, then reviewed. Two hand-edits were required:

1. `users.account_type` is added with a server default so the statement succeeds against a
   table that already holds rows, then the default is dropped — the column's value is a
   registration-time decision, not something the database should keep supplying. Existing
   accounts become vendors, which is what they were: the pre-portal product was a single
   bidder analysing tenders they had been sent.
2. Alembic's autogenerate compares tables and indexes but not CHECK constraints, so the
   constraint backing `AccountType` on the existing `users` table is written by hand. New
   tables get theirs from `create_table` and need no such help.

Revision ID: 0010
Revises: 0009
Create Date: 2026-07-28

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.domain.enums import AccountType

revision: str = "0010"
down_revision: str | None = "0009"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organisations",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("account_type", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("registration_number", sa.String(length=100), nullable=True),
        sa.Column("emirate", sa.String(length=32), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("address_line", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=False),
        sa.Column("contact_email", sa.String(length=320), nullable=False),
        sa.Column("contact_phone", sa.String(length=40), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("year_established", sa.SmallInteger(), nullable=True),
        sa.Column("employee_count", sa.Integer(), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "account_type IN ('company', 'vendor')", name=op.f("ck_organisations_account_type")
        ),
        sa.CheckConstraint(
            "emirate IN ('abu_dhabi', 'dubai', 'sharjah', 'ajman', 'umm_al_quwain', 'ras_al_khaimah', 'fujairah')",
            name=op.f("ck_organisations_emirate"),
        ),
        sa.CheckConstraint(
            "employee_count IS NULL OR employee_count >= 0",
            name=op.f("ck_organisations_employee_count_positive"),
        ),
        sa.CheckConstraint(
            "year_established IS NULL OR year_established BETWEEN 1800 AND 2200",
            name=op.f("ck_organisations_year_established"),
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_organisations_owner_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organisations")),
        sa.UniqueConstraint("id", "owner_user_id", name="uq_organisations_id_owner_user_id"),
        sa.UniqueConstraint("owner_user_id", name="uq_organisations_owner_user_id"),
    )
    op.create_index(
        "ix_organisations_account_type", "organisations", ["account_type"], unique=False
    )
    op.create_index("ix_organisations_emirate", "organisations", ["emirate"], unique=False)
    op.create_table(
        "password_reset_tokens",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("requested_ip_hash", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_password_reset_tokens_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_reset_tokens")),
    )
    op.create_index(
        op.f("ix_password_reset_tokens_token_hash"),
        "password_reset_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        "ix_password_reset_tokens_user_expires",
        "password_reset_tokens",
        ["user_id", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_reset_tokens_user_id"), "password_reset_tokens", ["user_id"], unique=False
    )
    op.create_table(
        "tender_listings",
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column("organisation_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("summary", sa.String(length=400), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("reference", sa.String(length=120), nullable=True),
        sa.Column("category", sa.String(length=48), nullable=False),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("emirate", sa.String(length=32), nullable=False),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("budget_min", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("budget_max", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("submission_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("questions_deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("contract_duration_months", sa.SmallInteger(), nullable=True),
        sa.Column("min_years_experience", sa.SmallInteger(), nullable=True),
        sa.Column("required_certifications", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.Column("requires_bid_bond", sa.Boolean(), nullable=False),
        sa.Column("bid_bond_percentage", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("cover_image_url", sa.String(length=500), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("application_count", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('construction_civil_works', 'roads_infrastructure', 'water_wastewater', 'electrical_power', 'oil_gas_petrochemical', 'renewable_energy', 'facilities_management', 'cleaning_waste_management', 'landscaping_irrigation', 'it_software', 'cybersecurity', 'cloud_data_centre', 'telecommunications', 'ai_data_analytics', 'healthcare_medical', 'education_training', 'transport_logistics', 'fleet_vehicles', 'security_services', 'catering_hospitality', 'printing_media', 'marketing_events', 'consulting_advisory', 'legal_services', 'financial_audit', 'hr_recruitment', 'furniture_fitout', 'laboratory_scientific', 'defence_aerospace', 'environmental_services')",
            name=op.f("ck_tender_listings_category"),
        ),
        sa.CheckConstraint(
            "emirate IN ('abu_dhabi', 'dubai', 'sharjah', 'ajman', 'umm_al_quwain', 'ras_al_khaimah', 'fujairah')",
            name=op.f("ck_tender_listings_emirate"),
        ),
        sa.CheckConstraint(
            "status = 'draft' OR published_at IS NOT NULL",
            name=op.f("ck_tender_listings_published_needs_timestamp"),
        ),
        sa.CheckConstraint(
            "status = 'draft' OR submission_deadline IS NOT NULL",
            name=op.f("ck_tender_listings_published_needs_deadline"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'published', 'closed', 'awarded', 'cancelled')",
            name=op.f("ck_tender_listings_status"),
        ),
        sa.CheckConstraint(
            "application_count >= 0", name=op.f("ck_tender_listings_application_count_positive")
        ),
        sa.CheckConstraint(
            "bid_bond_percentage IS NULL OR bid_bond_percentage BETWEEN 0 AND 100",
            name=op.f("ck_tender_listings_bid_bond_percentage_range"),
        ),
        sa.CheckConstraint(
            "budget_max IS NULL OR budget_max >= 0",
            name=op.f("ck_tender_listings_budget_max_positive"),
        ),
        sa.CheckConstraint(
            "budget_min IS NULL OR budget_max IS NULL OR budget_min <= budget_max",
            name=op.f("ck_tender_listings_budget_range"),
        ),
        sa.CheckConstraint(
            "budget_min IS NULL OR budget_min >= 0",
            name=op.f("ck_tender_listings_budget_min_positive"),
        ),
        sa.CheckConstraint(
            "min_years_experience IS NULL OR min_years_experience >= 0",
            name=op.f("ck_tender_listings_min_years_experience_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id", "owner_user_id"],
            ["organisations.id", "organisations.owner_user_id"],
            name="fk_tender_listings_organisation_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tender_listings")),
        sa.UniqueConstraint("id", "owner_user_id", name="uq_tender_listings_id_owner_user_id"),
        sa.UniqueConstraint(
            "organisation_id", "reference", name="uq_tender_listings_organisation_reference"
        ),
    )
    op.create_index(
        "ix_tender_listings_organisation", "tender_listings", ["organisation_id"], unique=False
    )
    op.create_index(
        "ix_tender_listings_owner_status",
        "tender_listings",
        ["owner_user_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_tender_listings_status_category",
        "tender_listings",
        ["status", "category"],
        unique=False,
    )
    op.create_index(
        "ix_tender_listings_status_deadline",
        "tender_listings",
        ["status", "submission_deadline"],
        unique=False,
    )
    op.create_index(
        "ix_tender_listings_status_emirate", "tender_listings", ["status", "emirate"], unique=False
    )
    op.create_table(
        "applications",
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_user_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_organisation_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("cover_letter", sa.Text(), nullable=True),
        sa.Column("bid_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("estimated_cost", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("proposed_duration_months", sa.SmallInteger(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("withdrawn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("first_viewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = 'draft' OR submitted_at IS NOT NULL",
            name=op.f("ck_applications_submitted_needs_timestamp"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'submitted', 'under_review', 'shortlisted', 'approved', 'rejected', 'withdrawn')",
            name=op.f("ck_applications_status"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('approved', 'rejected') OR decided_at IS NOT NULL",
            name=op.f("ck_applications_decided_needs_timestamp"),
        ),
        sa.CheckConstraint(
            "bid_amount IS NULL OR bid_amount >= 0",
            name=op.f("ck_applications_bid_amount_positive"),
        ),
        sa.CheckConstraint(
            "estimated_cost IS NULL OR estimated_cost >= 0",
            name=op.f("ck_applications_estimated_cost_positive"),
        ),
        sa.CheckConstraint(
            "proposed_duration_months IS NULL OR proposed_duration_months > 0",
            name=op.f("ck_applications_proposed_duration_positive"),
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["tender_listings.id"],
            name=op.f("fk_applications_listing_id_tender_listings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["vendor_organisation_id", "vendor_user_id"],
            ["organisations.id", "organisations.owner_user_id"],
            name="fk_applications_vendor_organisation_owner",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint("id", "vendor_user_id", name="uq_applications_id_vendor_user_id"),
        sa.UniqueConstraint("listing_id", "vendor_user_id", name="uq_applications_listing_vendor"),
    )
    op.create_index(
        "ix_applications_listing_status", "applications", ["listing_id", "status"], unique=False
    )
    op.create_index(
        "ix_applications_vendor_status", "applications", ["vendor_user_id", "status"], unique=False
    )
    op.create_index(
        "ix_applications_vendor_submitted",
        "applications",
        ["vendor_user_id", "submitted_at"],
        unique=False,
    )
    op.create_table(
        "listing_document_requirements",
        sa.Column("listing_id", sa.Uuid(), nullable=False),
        sa.Column("document_type", sa.String(length=48), nullable=False),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.SmallInteger(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "document_type IN ('trade_licence', 'commercial_registration', 'vat_tax_certificate', 'establishment_card', 'authorised_signatory', 'company_profile', 'audited_financials', 'bank_reference_letter', 'bid_bond', 'performance_guarantee', 'insurance_certificate', 'iso_certification', 'hse_plan', 'quality_plan', 'technical_proposal', 'commercial_proposal', 'method_statement', 'project_schedule', 'staff_cvs', 'organisation_chart', 'equipment_list', 'past_project_references', 'client_testimonial', 'other')",
            name=op.f("ck_listing_document_requirements_document_type"),
        ),
        sa.CheckConstraint(
            "weight BETWEEN 1 AND 10", name=op.f("ck_listing_document_requirements_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["tender_listings.id"],
            name=op.f("fk_listing_document_requirements_listing_id_tender_listings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_listing_document_requirements")),
        sa.UniqueConstraint(
            "listing_id", "document_type", name="uq_listing_document_requirements_listing_type"
        ),
    )
    op.create_index(
        "ix_listing_document_requirements_listing",
        "listing_document_requirements",
        ["listing_id"],
        unique=False,
    )
    op.create_table(
        "application_documents",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("vendor_user_id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("stored_filename", sa.String(length=80), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("extraction_status", sa.String(length=16), nullable=False),
        sa.Column("declared_document_type", sa.String(length=48), nullable=True),
        sa.Column("detected_document_type", sa.String(length=48), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "declared_document_type IS NULL OR declared_document_type IN ('trade_licence', 'commercial_registration', 'vat_tax_certificate', 'establishment_card', 'authorised_signatory', 'company_profile', 'audited_financials', 'bank_reference_letter', 'bid_bond', 'performance_guarantee', 'insurance_certificate', 'iso_certification', 'hse_plan', 'quality_plan', 'technical_proposal', 'commercial_proposal', 'method_statement', 'project_schedule', 'staff_cvs', 'organisation_chart', 'equipment_list', 'past_project_references', 'client_testimonial', 'other')",
            name=op.f("ck_application_documents_declared_document_type"),
        ),
        sa.CheckConstraint(
            "detected_document_type IS NULL OR detected_document_type IN ('trade_licence', 'commercial_registration', 'vat_tax_certificate', 'establishment_card', 'authorised_signatory', 'company_profile', 'audited_financials', 'bank_reference_letter', 'bid_bond', 'performance_guarantee', 'insurance_certificate', 'iso_certification', 'hse_plan', 'quality_plan', 'technical_proposal', 'commercial_proposal', 'method_statement', 'project_schedule', 'staff_cvs', 'organisation_chart', 'equipment_list', 'past_project_references', 'client_testimonial', 'other')",
            name=op.f("ck_application_documents_detected_document_type"),
        ),
        sa.CheckConstraint(
            "extraction_status IN ('pending', 'extracted', 'failed', 'unsupported')",
            name=op.f("ck_application_documents_extraction_status"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_application_documents_size_positive")),
        sa.ForeignKeyConstraint(
            ["application_id", "vendor_user_id"],
            ["applications.id", "applications.vendor_user_id"],
            name="fk_application_documents_application_vendor",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_documents")),
        sa.UniqueConstraint(
            "application_id", "sha256", name="uq_application_documents_application_sha256"
        ),
        sa.UniqueConstraint("storage_key", name="uq_application_documents_storage_key"),
    )
    op.create_index(
        "ix_application_documents_application",
        "application_documents",
        ["application_id"],
        unique=False,
    )
    op.create_index(
        "ix_application_documents_vendor", "application_documents", ["vendor_user_id"], unique=False
    )
    op.create_table(
        "application_screenings",
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("overall_score", sa.SmallInteger(), nullable=True),
        sa.Column("mandatory_met", sa.SmallInteger(), nullable=False),
        sa.Column("mandatory_total", sa.SmallInteger(), nullable=False),
        sa.Column("optional_met", sa.SmallInteger(), nullable=False),
        sa.Column("optional_total", sa.SmallInteger(), nullable=False),
        sa.Column("documents_processed", sa.Integer(), nullable=False),
        sa.Column("pages_extracted", sa.Integer(), nullable=False),
        sa.Column("pages_needing_ocr", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("scoring_version", sa.String(length=16), nullable=False),
        sa.Column("prompt_version", sa.String(length=16), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(length=32), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "error_code IS NULL OR error_code IN ('failed_validation', 'failed_extraction', 'failed_ai', 'failed_internal')",
            name=op.f("ck_application_screenings_error_code"),
        ),
        sa.CheckConstraint(
            "status <> 'completed' OR completed_at IS NOT NULL",
            name=op.f("ck_application_screenings_completed_needs_timestamp"),
        ),
        sa.CheckConstraint(
            "status = 'completed' OR overall_score IS NULL",
            name=op.f("ck_application_screenings_score_only_when_completed"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'processing', 'completed', 'failed')",
            name=op.f("ck_application_screenings_status"),
        ),
        sa.CheckConstraint(
            "mandatory_met <= mandatory_total",
            name=op.f("ck_application_screenings_mandatory_met_bounded"),
        ),
        sa.CheckConstraint(
            "mandatory_met >= 0 AND mandatory_total >= 0",
            name=op.f("ck_application_screenings_mandatory_counts"),
        ),
        sa.CheckConstraint(
            "optional_met <= optional_total",
            name=op.f("ck_application_screenings_optional_met_bounded"),
        ),
        sa.CheckConstraint(
            "optional_met >= 0 AND optional_total >= 0",
            name=op.f("ck_application_screenings_optional_counts"),
        ),
        sa.CheckConstraint(
            "overall_score IS NULL OR overall_score BETWEEN 0 AND 100",
            name=op.f("ck_application_screenings_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_application_screenings_application_id_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_screenings")),
        sa.UniqueConstraint("application_id", name="uq_application_screenings_application_id"),
    )
    op.create_index(
        "ix_application_screenings_score", "application_screenings", ["overall_score"], unique=False
    )
    op.create_index(
        "ix_application_screenings_status", "application_screenings", ["status"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("recipient_user_id", sa.Uuid(), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("listing_id", sa.Uuid(), nullable=True),
        sa.Column("application_id", sa.Uuid(), nullable=True),
        sa.Column("screening_score", sa.SmallInteger(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "type IN ('application_received', 'screening_completed', 'screening_failed', 'application_status_changed', 'deadline_approaching', 'listing_closed')",
            name=op.f("ck_notifications_type"),
        ),
        sa.CheckConstraint(
            "screening_score IS NULL OR screening_score BETWEEN 0 AND 100",
            name=op.f("ck_notifications_screening_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["applications.id"],
            name=op.f("fk_notifications_application_id_applications"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["tender_listings.id"],
            name=op.f("fk_notifications_listing_id_tender_listings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_user_id"],
            ["users.id"],
            name=op.f("fk_notifications_recipient_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_recipient_created",
        "notifications",
        ["recipient_user_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_notifications_recipient_unread",
        "notifications",
        ["recipient_user_id", "read_at"],
        unique=False,
    )
    op.create_table(
        "screening_findings",
        sa.Column("screening_id", sa.Uuid(), nullable=False),
        sa.Column("document_type", sa.String(length=48), nullable=False),
        sa.Column("verdict", sa.String(length=24), nullable=False),
        sa.Column("is_mandatory", sa.Boolean(), nullable=False),
        sa.Column("weight", sa.SmallInteger(), nullable=False),
        sa.Column("matched_document_id", sa.Uuid(), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=True),
        sa.Column("source_page", sa.Integer(), nullable=True),
        sa.Column("evidence_quote", sa.Text(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "document_type IN ('trade_licence', 'commercial_registration', 'vat_tax_certificate', 'establishment_card', 'authorised_signatory', 'company_profile', 'audited_financials', 'bank_reference_letter', 'bid_bond', 'performance_guarantee', 'insurance_certificate', 'iso_certification', 'hse_plan', 'quality_plan', 'technical_proposal', 'commercial_proposal', 'method_statement', 'project_schedule', 'staff_cvs', 'organisation_chart', 'equipment_list', 'past_project_references', 'client_testimonial', 'other')",
            name=op.f("ck_screening_findings_document_type"),
        ),
        sa.CheckConstraint(
            "verdict IN ('present', 'present_expired', 'present_unreadable', 'missing', 'not_applicable')",
            name=op.f("ck_screening_findings_verdict"),
        ),
        sa.CheckConstraint(
            "verdict NOT IN ('present', 'present_expired') OR matched_document_id IS NOT NULL",
            name=op.f("ck_screening_findings_present_needs_document"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_screening_findings_confidence_range"),
        ),
        sa.CheckConstraint(
            "source_page IS NULL OR source_page >= 1",
            name=op.f("ck_screening_findings_source_page_positive"),
        ),
        sa.CheckConstraint(
            "weight BETWEEN 1 AND 10", name=op.f("ck_screening_findings_weight_range")
        ),
        sa.ForeignKeyConstraint(
            ["matched_document_id"],
            ["application_documents.id"],
            name=op.f("fk_screening_findings_matched_document_id_application_documents"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["screening_id"],
            ["application_screenings.id"],
            name=op.f("fk_screening_findings_screening_id_application_screenings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_screening_findings")),
        sa.UniqueConstraint(
            "screening_id", "document_type", name="uq_screening_findings_screening_type"
        ),
    )
    op.create_index(
        "ix_screening_findings_screening", "screening_findings", ["screening_id"], unique=False
    )
    # ### end Alembic commands ###

    # Hand-written: NOT NULL against a populated table needs a default for the existing rows,
    # and the model declares no server_default, so it is dropped again immediately.
    op.add_column(
        "users",
        sa.Column(
            "account_type",
            sa.String(length=16),
            nullable=False,
            server_default=AccountType.VENDOR.value,
        ),
    )
    op.alter_column("users", "account_type", server_default=None)
    op.create_check_constraint(
        "account_type",
        "users",
        f"account_type IN ({AccountType.sql_in_list()})",
    )


def downgrade() -> None:
    op.drop_constraint(op.f("ck_users_account_type"), "users", type_="check")
    op.drop_column("users", "account_type")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_screening_findings_screening", table_name="screening_findings")
    op.drop_table("screening_findings")
    op.drop_index("ix_notifications_recipient_unread", table_name="notifications")
    op.drop_index("ix_notifications_recipient_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index("ix_application_screenings_status", table_name="application_screenings")
    op.drop_index("ix_application_screenings_score", table_name="application_screenings")
    op.drop_table("application_screenings")
    op.drop_index("ix_application_documents_vendor", table_name="application_documents")
    op.drop_index("ix_application_documents_application", table_name="application_documents")
    op.drop_table("application_documents")
    op.drop_index(
        "ix_listing_document_requirements_listing", table_name="listing_document_requirements"
    )
    op.drop_table("listing_document_requirements")
    op.drop_index("ix_applications_vendor_submitted", table_name="applications")
    op.drop_index("ix_applications_vendor_status", table_name="applications")
    op.drop_index("ix_applications_listing_status", table_name="applications")
    op.drop_table("applications")
    op.drop_index("ix_tender_listings_status_emirate", table_name="tender_listings")
    op.drop_index("ix_tender_listings_status_deadline", table_name="tender_listings")
    op.drop_index("ix_tender_listings_status_category", table_name="tender_listings")
    op.drop_index("ix_tender_listings_owner_status", table_name="tender_listings")
    op.drop_index("ix_tender_listings_organisation", table_name="tender_listings")
    op.drop_table("tender_listings")
    op.drop_index(op.f("ix_password_reset_tokens_user_id"), table_name="password_reset_tokens")
    op.drop_index("ix_password_reset_tokens_user_expires", table_name="password_reset_tokens")
    op.drop_index(op.f("ix_password_reset_tokens_token_hash"), table_name="password_reset_tokens")
    op.drop_table("password_reset_tokens")
    op.drop_index("ix_organisations_emirate", table_name="organisations")
    op.drop_index("ix_organisations_account_type", table_name="organisations")
    op.drop_table("organisations")
    # ### end Alembic commands ###
