"""certificate registry, and the unverified screening verdict

Adds the accreditation register screening checks an uploaded ISO certificate against, and
widens `screening_findings.verdict` to admit `present_unverified` — the verdict for a
certificate that was supplied and read but whose number is not in the register. Alembic
compares tables and indexes but not CHECK constraints, so the constraint swap is written by
hand from the enum rather than autogenerated.

Revision ID: 0012
Revises: 0011
Create Date: 2026-07-28

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.domain.enums import DocumentScreeningVerdict


revision: str = "0012"
down_revision: str | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificate_registry",
        sa.Column("certificate_number", sa.String(length=64), nullable=False),
        sa.Column("display_number", sa.String(length=80), nullable=False),
        sa.Column("standard", sa.String(length=40), nullable=False),
        sa.Column("issued_to", sa.String(length=255), nullable=False),
        sa.Column("issuing_body", sa.String(length=160), nullable=False),
        sa.Column("scope", sa.String(length=400), nullable=True),
        sa.Column("issued_on", sa.Date(), nullable=True),
        sa.Column("expires_on", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('active', 'expired', 'suspended', 'withdrawn')",
            name=op.f("ck_certificate_registry_status"),
        ),
        sa.CheckConstraint(
            "expires_on IS NULL OR issued_on IS NULL OR issued_on <= expires_on",
            name=op.f("ck_certificate_registry_issue_before_expiry"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_certificate_registry")),
    )
    op.create_index(
        op.f("ix_certificate_registry_certificate_number"),
        "certificate_registry",
        ["certificate_number"],
        unique=True,
    )
    op.create_index(
        "ix_certificate_registry_standard", "certificate_registry", ["standard"], unique=False
    )
    # ### end Alembic commands ###

    # Hand-written: `present_unverified` is a new member of DocumentScreeningVerdict.
    op.drop_constraint(op.f("ck_screening_findings_verdict"), "screening_findings", type_="check")
    op.create_check_constraint(
        "verdict",
        "screening_findings",
        f"verdict IN ({DocumentScreeningVerdict.sql_in_list()})",
    )


def downgrade() -> None:
    # Any row already carrying the new verdict would violate the narrower constraint, so those
    # findings are folded back to `missing` — the closest pre-existing meaning — before it is
    # reinstated. Their notes still record what was actually checked.
    op.execute(
        "UPDATE screening_findings SET verdict = 'missing' WHERE verdict = 'present_unverified'"
    )
    op.drop_constraint(op.f("ck_screening_findings_verdict"), "screening_findings", type_="check")
    op.create_check_constraint(
        "verdict",
        "screening_findings",
        "verdict IN ('present', 'present_expired', 'present_unreadable', 'missing', "
        "'not_applicable')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_certificate_registry_standard", table_name="certificate_registry")
    op.drop_index(
        op.f("ix_certificate_registry_certificate_number"), table_name="certificate_registry"
    )
    op.drop_table("certificate_registry")
    # ### end Alembic commands ###
